# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ac66d082d5055719d890099a29267a215197f0ded931ac2e0ed7be4f50122c626e9fa9b777d0f9740e764fbdc0baed3ebc081ab354b8d3612464d9b8240c644

test:
  secret_key_base: 370a071340d6908ce9da836c3422f611034b22003290a51223813cc5e372d57cd6ef5a54b5d89fd0f1b21f1922989f93c0f6573e13607ff13b98345809439725

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
